import { NextResponse } from 'next/server'

const flag = 'RIVAN{idor_broken_access_control}'
const sessions = new Map<string, { login: boolean; resource: boolean; unauthorized: boolean; submitted: boolean }>()
type Context = { params: Promise<{ path: string[] }> }
function getSession(request: Request) { const cookie = request.headers.get('cookie')?.match(/hr_session=([^;]+)/)?.[1] ?? crypto.randomUUID(); const progress = sessions.get(cookie) ?? { login: false, resource: false, unauthorized: false, submitted: false }; sessions.set(cookie, progress); return { cookie, progress } }
function json(body: unknown, init: ResponseInit = {}, cookie?: string) { const result = NextResponse.json(body, init); if (cookie) result.cookies.set('hr_session', cookie, { httpOnly: true, sameSite: 'lax', path: '/' }); return result }
export async function GET(request: Request, context: Context) { const { path = [] } = await context.params; const endpoint = `/${path.join('/')}`; const { cookie, progress } = getSession(request); if (endpoint === '/api/progress') return json({ robots: progress.login, javascript: progress.resource, idor: progress.unauthorized, briefing: progress.unauthorized, submitted: progress.submitted }, {}, cookie); if (endpoint === '/api/employees') { if (!progress.login) return json({ error: 'authentication required' }, { status: 401 }, cookie); const id = new URL(request.url).searchParams.get('id'); if (id === '1001') { progress.resource = true; return json({ id, name: 'Jordan Lee', department: 'Operations', role: 'Coordinator' }, {}, cookie) } if (id === '1002') { progress.unauthorized = true; return json({ id, name: 'Mara Ellison', department: 'People Operations', role: 'HR Director', internalResource: '/api/restricted-briefing', flag }, {}, cookie) } return json({ error: 'employee not found' }, { status: 404 }, cookie) } if (endpoint === '/api/restricted-briefing' && progress.unauthorized) return json({ title: 'Restricted HR briefing', flag }, {}, cookie); return json({ error: 'not found' }, { status: 404 }, cookie) }
export async function POST(request: Request, context: Context) { const { path = [] } = await context.params; const endpoint = `/${path.join('/')}`; const { cookie, progress } = getSession(request); const body = await request.json().catch(() => ({})) as Record<string, string>; if (endpoint === '/reset') { sessions.delete(cookie); const result = json({ reset: true }); result.cookies.set('hr_session', '', { httpOnly: true, sameSite: 'lax', path: '/', maxAge: 0 }); return result } if (endpoint === '/api/login') { if (body.email !== 'analyst@rivan.internal' || body.password !== 'rivan-analyst') return json({ error: 'Invalid email or password' }, { status: 401 }); progress.login = true; return json({ authenticated: true }, {}, cookie) } if (endpoint === '/submit') { if (!progress.unauthorized || body.flag?.trim() !== flag) return json({ accepted: false, error: 'Restricted resource access required.' }, { status: 403 }, cookie); progress.submitted = true; return json({ accepted: true }, {}, cookie) } return json({ error: 'not found' }, { status: 404 }, cookie) }
